no-transform overlay
YaLTeR/SourcePauseTool pull request #194
Opened 2022-01-27 23:13 UTC by UncraftedName

Added an overlay that does not transform the camera (I meant to push this along with sg collision stuff but forgot).
Why?
Well, when you're behind your saveglitch portal _and_ in contact with the portal hole, you have collision with geometry from the remote portal, _**but**_ your camera is also transformed to the other portal meaning that it can be difficult to figure out exactly where/what you have collision with.

For this video I saveglitched on blue and have enabled the following commands:
- `y_spt_draw_portal_env 1`
- `y_spt_draw_portal_env_remote 1`
- `_y_spt_overlay 1`
- `_y_spt_overlay_swap 1`
- `_y_spt_overlay_type 69420`

So the top left shows what you normally see, and in the main screen you can see where the player is and exactly what geometry you have collision with. Notice that as soon as I stop touching the portal hole, the normal view snaps to the actual player location and you lose collision with the remote geometry.

https://user-images.githubusercontent.com/34390438/151457715-64d20976-38cd-464a-a911-18f56e3b01ea.mp4

(Also, it makes sense for the overlay to do nothing by default.)

2022-01-28 17:00 UTC, lipsanen requested changes

2022-01-28 17:00 UTC, lipsanen commented on spt/features/overlay.cpp
> +                           "  anything else = no camera transform (even when behind SG portal)\n");
Add a fixed number here for the future, in case someone adds new overlay types.

2022-01-30 18:07 UTC, UncraftedName commented on spt/features/overlay.cpp
> +                           "  anything else = no camera transform (even when behind SG portal)\n");
I was thinking of making no transform the default, so if you add new overlays in the future you would add 4, 5, etc. Is that too weird?

2022-02-02 21:44 UTC, lipsanen commented on spt/features/overlay.cpp
> +                           "  anything else = no camera transform (even when behind SG portal)\n");
no transform being default as 0 would make some amount of sense but "super high value" default is kinda weird

2022-02-03 03:33 UTC, UncraftedName commented
as you wish

2022-02-03 03:40 UTC, UncraftedName commented
alright - what about this? set no transform to 0 & default, bumped up sg vision to 4

2022-02-03 16:31 UTC, lipsanen commented
not really a fan of changing existing behavior either, the primary use of the overlay is for sg purposes anyway so this will cause lots of complaints about "overlay not working in new spt"

2022-02-05 04:33 UTC, UncraftedName commented
far enough, simple solution it is

2022-02-05 12:52 UTC, merged

2022-02-05 12:52 UTC, lipsanen commented
Thanks!